version: '3'

services:
  mediawiki:
    image: mediawiki
    ports:
      - 8080:80
    links:
      - database
      - smtp
    volumes:
      - images:/var/www/html/images
      - ./files/LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - SMTP_HOST=smtp  # Set the SMTP server host
      - SMTP_PORT=1025 
    restart: always

  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
    restart: always

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always

  wordpress:
    depends_on:
      - db
      - smtp
    image: wordpress:latest
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      SMTP_HOST: smtp  # Set the SMTP server host
      SMTP_PORT: 1025  # Set the SMTP server port
    restart: always

  forum_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: forum_mysql_password
      MYSQL_DATABASE: forum_database
      MYSQL_USER: forum_user
      MYSQL_PASSWORD: forum_password
    volumes:
      - forum_db_data:/var/lib/mysql
    networks:
      - my_network
    restart: always

  forum:
    build:
      context: .
      dockerfile: forum/Dockerfile
    depends_on:
      - forum_db
    ports:
      - "8082:80"
    networks:
      - my_network
    environment:
      - SMTP_HOST=smtp  # Update SMTP server host
      - SMTP_PORT=587 
    restart: always
    volumes:
      - ./modif:/modif

  smtp:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI for viewing emails
    restart: always

  mailing:
   build:
     context: .
     dockerfile: mailing/Dockerfile
   ports:
     - "8086:8086"
   restart: always
   environment:
     - to=denoyelle.boris@gmail.com
     - from=denoyelle.boris@gmail.com
     - pwd=${PASSWORD:-default_value}
  
  landing:
    build:
      context: .
      dockerfile: landing/Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  images:
  db:
  db_data:
  forum_db_data:

networks:
  my_network:

